modLoader="javafml"
license="All Rights Reserved unless stated otherwise. Distrubtion permssion is given to FeedTheBeast and CurseForge for use in modpacks"
loaderVersion="[30,)"
[[mods]]
    modId="javd"
    version="${file.jarVersion}"
    displayName="Just Another Void Dim"
    description="Void Worlds"
